davidkastner/quantumPDB

- README.md
- docs/autosummary/qp.checks.fetch_pdb.rst
- docs/autosummary/qp.checks.rst
- docs/autosummary/qp.cluster.coordination_spheres.rst
- docs/autosummary/qp.cluster.rst
- docs/autosummary/qp.structure.add_hydrogens.rst
- docs/autosummary/qp.structure.missing_loops.rst
- docs/autosummary/qp.structure.rst
- docs/conf.py
- qp/checks/__init__.py
- qp/checks/fetch_pdb.py
- qp/cli.py
- qp/cluster/__init__.py
- qp/cluster/coordination_spheres.py
- qp/structure/__init__.py
- qp/structure/add_hydrogens.py
- qp/structure/missing_loops.py
Calculating charge:
- `add_hydrogens.download` now supports downloading Protoss SDF files in addition to PDBs. These can be used to calculate the total charge of ligands.
- `coordination_spheres.extract_clusters` has an option for calculating the total charge of coordinating AAs and writing to an output csv.
Updated docstrings with simple usage examples.
> Added charge calculation and updated documentation

- environment.yml
- pyproject.toml
- qp/_version.py
Updated the project toml to the correct shortcut name
> Update build to include shortcut

- qp/_version.py
- qp/cluster/coordination_spheres.py
- scripts/cluster_sizes.py
- scripts/doi.py
- scripts/new_master.py
- scripts/qp_job_manager.py
I added scripts that can be used for submitting the quantumPDB generated dataset. They are functional but still in the testing phase. They will eventually be combined with the quantumPDB CLI workflow.
> Job manager scripts

- qp/cluster/coordination_spheres.py
The script was not including the coordinating ligands if they were non-amino acids. I updated the script so that it now includes any ligand that coordinates the metal regardless of whether it is specified in the input script.
> Include ligands in first sphere

- qp/cli.py
- qp/cluster/coordination_spheres.py
- qp/structure/add_hydrogens.py
- qp/structure/missing_loops.py
I updated the code to handle several common modes of failure that I was observing. The chains are now labeled correctly. I remove insertion tags that are added by modeller and label the N-terminal nitrogen atom with a unique atom name which allows us to tell if it ends up in the cluster model which happens occasionally.
> Updated the code to handle a variety of failure modes

- qp/structure/missing_loops.py
- scripts/count_chains.py
Added a new script for counting the total number of chains that end up in the dataset. This number is more interesting and useful than counting the number of proteins that are in the dataset as there may be many different chains in a single protein PDB and many of these chains are conformationally unique.
> Added a new script for counting the total number of chains

- environment.yml
- qp/cli.py
- scripts/charge_pca_analysis.py
Updated the PCA script to save out the principal components for each of the proteins and their chains. This is stored in the scripts folder rather than implemented in the quantumPDB CLI.
> Updated PCA script to save principal components

- docs/api.rst
- qp/cli.py
- qp/manager/job_manager.py
Added a new module called manager, which controls the submission and verification of the QM job submission process. It can be accessed through the main CLI.
> Integrated the job manager script into the CLI

- qp/cli.py
I updated the user prompts to be clearer in the batch request and the functional.
> Clarified user prompts

- qp/cli.py
- qp/manager/failure_checkup.py
- qp/manager/find_incomplete.py
- qp/manager/job_manager.py
Added a module that detects if any jobs in the master_protein_list.txt did not finish completely.
> Find unfinished jobs

- qp/cli.py
- qp/manager/job_manager.py
Updated the job manager to query a default master list for the oxidation state rather than generate both.
> Added functionality to query a master list

- qp/cli.py
Updated the user prompts for the job manager to be more intuitive and make use of the click prompt interface.
> Updated user prompts

- qp/cli.py
- qp/manager/__init__.py
- qp/manager/job_manager.py
I added an option to the CLI that controls whether or not the user would like to submit an optimization job. Prior to this bug fix all jobs were submitted as a geometry optimization.
> Added an option to perform minimization

- qp/cli.py
- qp/manager/failure_checkup.py
Updated the module that checks for failed jobs. It will now inspect the output of all the jobs and match the output to common failure modes.
> Added module to check for failed jobs

- qp/scripts/hydratase_identifier.py
Improved the hydratase plotting script.
> Minor improvements to the hydratase script

- qp/cli.py
- qp/cluster/coordination_spheres.py
Make the spheres more stable with respect to the ligands' different shapes at symmetric active sites
1. Open the cli interface for including water molecules in all coordination spheres.
2. Add water molecules and ligands in a post-processing scheme: they are included but not shown in the frontiers of the spheres, but added after all the sphere is completed.
> Post-addition of coordinating ligands

- qp/cli.py
- qp/cluster/coordination_spheres.py
Merging in three different methods of smoothing the spheres: 1) box plot, 2) density clustering, and 3) dummy atoms.
> Sphere smooth

- qp/cli.py
- qp/cluster/coordination_spheres.py
- qp/structure/add_hydrogens.py
- qp/structure/missing_loops.py
Sometimes the N-terminus is inside the clusters, which means we need to be able to identify it and increase the net charge of the cluster by 1 as it will be protonated. I had previously accomplished this by renaming the N-terminal nitrogen atom to "NT". This was a poor choose as it can cause issues in other places as the code is being improved. I changed the code so that the N-terminus is found by looking for the final residue in `structure`.
> Changed how the N-terminal residues are identified

- qp/scripts/distance_to_metal.py
I added a new script to the `scripts` directory, which allows the user to quickly analyze the distances between the iron center and all other atoms in each of the clusters. This is a good method of identifying the extent of outliers and problematic edge cases.
> Added a new script for ananalyzing metal-atom distances

- qp/scripts/atom_counts.py
- qp/scripts/atom_counts_stripplot.py
I added a set of scripts that aid in computing the atom counts of the cluster models for different methods.
> Added scripts to analyze atom counts

- qp/cli.py
- qp/cluster/coordination_spheres.py
1. Build the first sphere with the "coordinative" heavy atoms within a distance cutoff (as an option in cli prompts), while other outer spheres with Voronoi neighborhoods
2. Add a check for nitrogen atoms in the first sphere to exclude the positively charged ones
3. Remove the options on including the ligands and water molecules
4. Add docstrings for new auxiliary functions
> Mixed approach of spheres

- qp/checks/to_xyz.py
- qp/cluster/coordination_spheres.py
- qp/manager/job_manager.py
Made two new changes to the code. The first was to update the job manager to work better with the master list in computing the expected oxidation state and multiplicity. The second was I updated the xyz generating function so that it will make multiple different xyz files that can be used later.
> Create multiple xyz files depending on requested spheres

- qp/cli.py
- qp/manager/job_manager.py
I updated job manager such that it will download the newest version of the non-heme iron protein master list and use the values from the oxidation state, and spin state columns to calculate the multiplicity for QM jobs.
> Updated job manager

- qp/manager/failure_checkup.py
- qp/manager/job_manager.py
Updated failure_checkup.py so that it will also produce a plot to visualize the different failure modes.
> Updated the checkup script to also plot the results

- qp/cli.py
- qp/cluster/coordination_spheres.py
- qp/structure/add_hydrogens.py
- qp/structure/missing_loops.py
1. **Backbone nitrogen coordination**: check if nitrogens in the backbone are coordinated with the metal, and remove their hydrogens added by protoss.
2. **NO ligands**: remove all the hydrogen attached by protoss as a hydroxylamine.
3. **Histidine coordination**: check if the *N*-coordinated conformation is possible, and flip the imidazole ring to have it coordinated.
4. **Adding hydrogens to CSO**: Add hydrogen to CSO's carbons and the hydroxyl oxygen by geometric rules. The case that the TAN ligand is in an addition reaction with CSO is given special consideration, where the hydroxyl group is deprotonated.
5. **Isonitrile ligands**: remove hydrogens in all ligands which is to close to the metal.
6. **Charge calculation**: detect hydrogen removal in the backbone and ligands in addition …
> Fix special errors met in Nitrile Hydratase family

- qp/manager/job_manager.py
Previously job manager needed to be resubmitted by the user. Now the user can specify how many jobs they would like running at one time and job manager will continuous check the queue to make sure the jobs maintain that requested number.
> Automated job manager to include automatic resubmissions

- qp/manager/job_manager.py
Added several bug fixes to the job manager. First, the job manager was trying to resubmit failed jobs. Second, it was not correctly identifying jobs that were on the queue as already having been submitted. Both of these have been fixed. I also added functionality such that the job manager will now generate a `.submit-record` as soon as a job has been added to the queue. This is useful to help keep track of which jobs have been submitted and are still waiting to run. This fail contains some useful information that can be used for troubleshooting and tracking down failed jobs.
> Generate submit records as hidden files

- CITATION.cff
Added a CITATIONS.cff file to make it easier to cite the package.
> Adding a citations file

- config.yaml
- environment.yml
- qp/cli.py
A quantumPDB job was originally previously initiated only using the command line. This meant that the user had to enter a lot of different values and they would have to re-enter them every time that they wanted to change something. As we continue to grow qp, the number of values was only going to increase. This meant we needed to transition to a yaml based input to make it more flexible and easier for the user.
> Transition to a yaml based input

- qp/_version.py
- qp/cli.py
- qp/manager/job_manager.py
Update the job manager module so that it makes use of the config.yaml file and the new master list format.
> Generalize the job manager to the new format

- qp/cli.py
- qp/cluster/coordination_spheres.py
- Sorts residues based on closest distance from any of the residue's atoms to any of the cluster center's atoms
- Removes residues until total atom count is less than `max_atom_count`
- Note: pruning is done before capping, so final atom count may end up slightly over `max_atom_count`
> Add max atom count parameter

- config.yaml
- qp/cli.py
- qp/cluster/coordination_spheres.py
`include_ligands` options:          
Only ligands and waters in the first sphere (0), Only non-water ligands (1), Everything (2)
> Include small molecules in different ways

- config.yaml
- qp/_version.py
- qp/cli.py
For every cluster model, a PDB is constructed that includes all of the residues. Previously, HETATMS and iron were being excluded for a separate project. I have updated qp so that these generated PDBs will no include Fe and HETATMs.
> Include HETATMs in final PDB

- qp/manager/job_scripts_supercloud.py
We would like quantumPDB to run on SuperCloud in an easy way. However, for the moment, we are adding the script so that it can be tested before finding a more generalizable solution.
> Add scripts for running on supercloud

- qp/cli.py
- qp/structure/convert_to_oxo.py
- qp/structure/prompt.txt
Added a new module that allows the user to automatically generate the reactive oxo and succinate state from an alpha-ketoglutarate NHIE state.
> Can generate oxo state from AKG state

- qp/structure/add_hydrogens.py
Recheck center residues when they are partially occupied. A tighter threshold (1.0 angstrom) is used for its neighbors)
> recheck center residues

- qp/cli-old.py
- qp/structure/convert_to_oxo-old.py
In the previous version of the oxo generator, the oxo and succinate would get generated at the modeller step. This did not work well since many of the prepared jobs start from the Protoss step. I updated qp so that the oxo and succinate will get generated from the Protoss structure.
> Update oxo generator

- qp/cluster/coordination_spheres.py
- qp/structure/add_hydrogens.py
As an alternative of capping method, the valence-awared, geometry-based capping algorithm detects if the N or C termini of an amino acid residue in the middle of a chain is neither linked with another amino acid residue nor has enough valences. It's supposed to solve the problem when relaxation-protonation iterations don't save the residues deleted by Protoss
> Valence-based-capping

- config.yaml
- qp/cli.py
- qp/job_manager/failure_checkup.py
I updated the failure checkup module to work with the new yaml and more general settings and the updates to the overall file structure. It is a useful way to get a quick snapshot of how a specific dataset is doing.
> Updated the failure check in module

- qp/cli.py
Quick bug fix where an extra parameter needed to be removed that was throwing an error.
> Bug fix in manager

- qp/analyze/molden.py
- qp/analyze/multiwfn.py
- qp/cli.py
Several of the module names needed to be updated in the analyze subpackage and were throwing errors.
> Module naming issue

- qp/protonate/ligand_prop.py
Added CS and CD as they have constant oxidation states such that their charges will be handled automatically.
> Added CS and CD

- qp/manager/job_scripts.py
Previously qp would run the terachem jobs locally. However, to adhere to best practices or our cluster, we updated the job_scripts.py to use the scratch directory on the compute nodes.
> Use the scratch directory when running jobs

- qp/manager/job_scripts.py
Updated the slurm script to be simpler so that it doesn't require the scratch directory.
> Updated SLURM script

- qp/analyze/multiwfn.py
More robust handling of jobs in the dipole and charge calculations of the Analyze subpackage such that it won't die if a molden is missing
> Avoid fails on missing moldens
